### ISSUE TITLE
Examples Intermediate_Globe dosen’t work in gold version

### ISSUE THREAD

**Issue by adzhikemalov** [away3d/away3d-examples-fp11#4]

**Comment by richardolsson** [comment]
@rob-bateman Do you mind having a look at this?

**Comment by adzhikemalov** [comment]
[Fault] exception, information=ArgumentError: Error #1063: Argument count mismatch onIntermediate_Globe/modulateDiffuseMethod(). Expected 2, got 3.
In BasicDiffuseMethod.as line 185

**Comment by rob-bateman** [comment]
fix committed to master 8168d7c3e67efb4daff766a5a2d331e66a38ba9c
